version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/sway-easyshot
    binary: sway-easyshot
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w
      - -s
archives:
  - name_template: >-
      {{ .Binary }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"

release:
  prerelease: "false"

nfpms:
  - file_name_template: >-
      sway-easyshot-
      {{- .Version}}_{{.Os}}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    homepage: https://github.com/chmouel/sway-easyshot
    description: "sway-easyshot - A webhook and https://smee.io forwarder"
    maintainer: Chmouel Boudjnah <chmouel@chmouel.com>
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./misc/sway-easyshot-server.service
        dst: /etc/systemd/system/sway-easyshot-server.service
        type: "config|noreplace"
      - src: ./misc/sway-easyshot.service
        dst: /etc/systemd/system/sway-easyshot-client.service
        type: "config|noreplace"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Brew formula update"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - Update README.md

aurs:
  - name: sway-easyshot-bin
    homepage: "https://github.com/chmouel/sway-easyshot"
    description: "sway-easyshot - Sway Screenshot control"
    maintainers:
      - "Chmouel Boudjnah <chmouel@chmouel.com>"
    license: Apache 2.0
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/sway-easyshot-bin.git
    package: |-
      install -Dm755 "./sway-easyshot" "${pkgdir}/usr/bin/sway-easyshot"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/sway-easyshot/LICENSE"
